### ISSUE TITLE
just a quick question....

### ISSUE THREAD

**Issue by billonthebeach** [bradfrost/this-is-responsive#11]
V! .. used responsive slides on another project recently... nice piece of work... install and customization was quick and easy.....  Thanks!

Now on the next project..

A "simple yes or no "as to whether or not it is possible to mix media.. specially .jpegs and .flv files would be appreciated.   And  if mixing media is possible, any hints so I can get off to a quick start might get you a twelve pack!

Thanks again.
Bill

**Comment by bradfrost** [comment]
I'm afraid I didn't make responsive slides, so I don't think I can answer your question. Sorry!

**Comment by billonthebeach** [comment]
no problem... thanks for getting back with me anyway....

Best Regards,
bill
