### ISSUE TITLE
Cons for dropdown breadcrumbs don't look right.

### ISSUE THREAD

**Issue by eyesofjeremy** [bradfrost/this-is-responsive#31]
One of the cons for the [dropdown breadcrumb pattern](http://codepen.io/bradfrost/full/DCgax) is:
"Small screen users require a full-page refresh in order to go back multiple levels"

but that's the same for the [last one only](http://codepen.io/bradfrost/full/dKulf) pattern, and not the case here. The dropdown is explicitly to avoid that ...

HTH,
Jeremy

**Comment by equivalentideas** [comment]
It also seems like 'Last One Only Breadcrumbs' has got a _pro_ from the Dropdown Breadcrumb pattern:

> Small screen users are still able to traverse the breadcrumb trail

isn't this _not_ the case? That's why it's the 'last one only'... I feel like I'm missing something and have made a fool of myself.

**Comment by bradfrost** [comment]
Hi all,
Thanks for pointing this out. I've updated the CodePen with new cons that aren't duplicates of the last-one only: http://codepen.io/bradfrost/full/DCgax

Thanks agian!
