### ISSUE TITLE
Define default branch "gh-page" on your repository administration

### ISSUE THREAD

**Issue by oziks** [bradfrost/this-is-responsive#4]

**Comment by bradfrost** [comment]
Thanks! I had no idea you could do that, so now the gh-pages branch is now the default. Thanks again!

**Comment by oziks** [comment]
It's also possible to add a website to your repository github ;)

**Comment by bradfrost** [comment]
What do you mean?

**Comment by oziks** [comment]
To access your gh-page easier !
Like this repository https://github.com/fabpot/Silex, the description is followed by a website address.

**Comment by bradfrost** [comment]
Awesome, is that difficult to set up? I already have the domain.

**Comment by oziks** [comment]
check this out https://help.github.com/articles/setting-up-a-custom-domain-with-pages.
