### ISSUE TITLE
404 Link for "An agency workflow for Responsive Web Design"

### ISSUE THREAD

**Issue by marszu** [bradfrost/this-is-responsive#62]
Hi 
on the http://bradfrost.github.io/this-is-responsive/resources.html
Process link to the "An agency workflow for Responsive Web Design"
is dead 
http://bradfrost.github.io/this-is-responsive/An%20agency%20workflow%20for%20Responsive%20Web%20Design

I guess you meant this link. 
http://www.elezea.com/2013/09/responsive-design-agency-workflow/

**Comment by bradfrost** [comment]
Thanks, fixed!
