### ISSUE TITLE
New resource for Frameworks/Boilerplates/Prototyping

### ISSUE THREAD

**Issue by knutila** [bradfrost/this-is-responsive#85]
Moboom (http://moboom.com), an adaptive CMS and responsive design tool.

**Comment by bradfrost** [comment]
Hey @knutila,
Thanks for sharing Moboom. What exactly is it? It doesn't look like a framework or prototyping tool in the same sense as the other items on the list.

Perhaps it would go under CMSes?

**Comment by knutila** [comment]
Hey Brad,
It would definitely fit under CMS, maybe that's the best fit.

Moboom is both a CMS and a design tool. Designers use it to prototype and
build sites as well as manage content. More info here:
http://moboom.com/platform.

Thank you!
James

On Fri, Apr 4, 2014 at 9:54 AM, Brad Frost notifications@github.com wrote:

> Hey @knutila https://github.com/knutila,
> Thanks for sharing Moboom. What exactly is it? It doesn't look like a
> framework or prototyping tool in the same sense as the other items on the
> list.
> 
> Perhaps it would go under CMSes?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/bradfrost/this-is-responsive/issues/85#issuecomment-39586656
> .

## 

James Knutila
Inbound Marketing Manager
Moboom | Design Responsively(tm)
james@moboom.com
+1 484 695 7288

**Comment by bradfrost** [comment]
Thanks for the clarification. I added a new section under the CMS section: http://bradfrost.github.io/this-is-responsive/resources.html
