### ISSUE TITLE
Dynamic layouts : Brickwork

### ISSUE THREAD

**Issue by iraycd** [bradfrost/this-is-responsive#88]
[BrickWork](http://iraycd.github.io/brickwork/) is used to create a dynamic layout grid.

Example:
[Pinterest Design](http://iraycd.github.io/brickwork/examples/pinterest/)
[Draggable Bricks](http://iraycd.github.io/brickwork/examples/draggable/)

**Comment by bradfrost** [comment]
Thanks for sharing, @iraycd! I added a new section under Layout for JS-based layout solutions: http://bradfrost.github.io/this-is-responsive/resources.html
