### ISSUE TITLE
images do not load...

### ISSUE THREAD

**Issue by busticated** [bradfrost/this-is-responsive#89]
http://bradfrost.github.io/this-is-responsive/patterns/images/fpo_square.png
http://bradfrost.github.com/this-is-responsive/patterns/images/fpo_square.png

as featured in such fine examples as:

http://codepen.io/bradfrost/full/GlrHv

and

http://codepen.io/bradfrost/full/xkcBn

**Comment by bradfrost** [comment]
Hey @busticated,
Thanks for bringing this up. These images have been restored so you should be good to go!

**Comment by busticated** [comment]
nice! :clap:

thanks for making & sharing such a great resource!
