### ISSUE TITLE
New links about Guide To Flexbox - for Tutorials section

### ISSUE THREAD

**Issue by taliscope** [bradfrost/this-is-responsive#99]
Hello Brad,

<p>Here are some useful new links about Guide To Flexbox, for your Tutorials section</p>

<p>
<a href="http://demosthenes.info/blog/780/A-Designers-Guide-To-Flexbox">
A Designer’s Guide To Flexbox, Part 1: Basic Example of Flexbox in Action</a><br>
<a href="http://demosthenes.info/blog/787/A-Designers-Guide-To-Flexbox-Part-2-Going-Vertical">
A Designer’s Guide To Flexbox, Part 2: Going Vertical</a><br>
<a href="http://demosthenes.info/blog/901/A-Designers-Guide-To-Flexbox-Understanding-Visual-Weight">
A Designer’s Guide To Flexbox, Part 3: Understanding Visual Weight</a><br>
<a href="http://demosthenes.info/blog/920/A-Designers-Guide-To-Flexbox-Order">
A Designer’s Guide To Flexbox, Part 4: Order</a><br>
<a href="http://demosthenes.info/blog/778/A-Responsive-Graphic-Novel-In-Flexbox">
A Designer’s Guide To Flexbox, Part 5: A Responsive Graphic Novel In Flexbox</a><br>
<a href="http://demosthenes.info/blog/844/Easy-Masonry-Layout-With-Flexbox">
A Designer’s Guide To Flexbox, Part 6: Easy Masonry Layout With Flexbox</a><br>
<a href="http://demosthenes.info/blog/854/Easy-Responsive-Grid-Layout-With-Flexbox">
A Designer’s Guide To Flexbox, Part 7: Easy Responsive Grid Layout With Flexbox</a><br>
</p>

Have a nice day and God bless

**Comment by bradfrost** [comment]
@taliscope Thanks for this! Looks interesting.
